name: Programtest

on: push

jobs:
        build_and_run_tests:
                runs-on: ubuntu-latest
                container: tibix2310/mosze:latest
                steps: 
                - uses: actions/checkout@v2

                - run: make programTest
