
name: TestOutput

on: push

jobs:
        Testing:
                runs-on: ubuntu-latest
                steps: 
                - uses: actions/checkout@v2
                - run: sudo apt-get install -y valgrind cppcheck
                - run: cppcheck *.cpp --enable=warning --error-exitcode=1
                - run: cppcheck *.cpp --enable=warning,style,performance --output-file=test/styleperform.txt
                - uses: actions/upload-artifact@v2
                  with:
                        name: styleperform
                        path: ./test/styleperform.txt
                - run: clang++ -std=c++17 *.cpp -Wall -Wextra
                - run: valgrind --leak-check=full --error-exitcode=1 ./a.out scenario1.json
                - run: ./run-test.sh