name: TestOutput

on: push 

jobs:
	Test:
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v2
		- run: sudo apt-get install -y valgrind cppcheck
		- run: cppcheck *.cpp --enable=warning --error-exitcode=1
		- run: cppcheck *.cpp --enable=warning.warning.style.performance --output-file=testing/styleperform.txt
		- uses: actions/upload-artifact@v2
		  with:
			name: styleperform
			path: ./testing/styleperform.txt
		- run: clang++ *.cpp -Wall -Wextra
		- run: valgrind --leak-check=full --error-exitcode=1 ./a.out testing/units/advHalis.json testing/units/codos.json
		- run: ./run-test.sh
